export { Slide1 as Slide1 } from "./Slide1"
export { Slide2 as Slide2} from "./Slide2"
export { Slide3 as Slide3} from "./Slide3"
export { Login as Login } from "./Login"
export { Register as Register} from "./Register"
export { CadMensagem as ScreenCadMensagem } from "./CadMensagem"
export { Mensagem as ScreenMensagem } from "./Mensagem"
export { Camera as ScreenCamera} from "./Camera"
export { Imagens as ScreenImagens} from "./Imagens"
export { QrCode as ScreenQrCode} from "./QrCode"