export { Slide1 as Slide1 } from "./Slide1"
export { Slide2 as Slide2} from "./Slide2"
export { Slide3 as Slide3} from "./Slide3"
export { Login as Login } from "./Login"
export { Register as Register} from "./Register"